---
openapi: "3.0.0"
info:
  title: IETF @ - Author Tools API
  version: 0.0.1
servers:
  - url: http://devbox.amsl.com:55555
    description: Alpha server
paths:
  /api/render/text:
    post:
      summary: Returns rendered draft in text format.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: kramdown-rfc2629 (.md, .mkd) file or xml2rfc v2/v3 (.xml) file or text draft (.txt)
      responses:
        '200':
          description: Returns draft in requested format.
          content:
            text/plain:
              schema:
                type: string
        '400':
          description: Error has occured.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error description
  /api/render/xml:
    post:
      summary: Returns rendered draft in xml2rfc v3 format.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: kramdown-rfc2629 (.md, .mkd) file or xml2rfc v2/v3 (.xml) file or text draft (.txt)
      responses:
        '200':
          description: Returns draft in requested format.
          content:
            application/xml:
              schema:
                type: string
        '400':
          description: Error has occured.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error description
  /api/render/html:
    post:
      summary: Returns rendered draft in HTML format.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: kramdown-rfc2629 (.md, .mkd) file or xml2rfc v2/v3 (.xml) file or text draft (.txt)
      responses:
        '200':
          description: Returns draft in requested format.
          content:
            text/html:
              schema:
                type: string
        '400':
          description: Error has occured.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error description
  /api/render/pdf:
    post:
      summary: Returns rendered draft in PDF format.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: kramdown-rfc2629 (.md, .mkd) file or xml2rfc v2/v3 (.xml) file or text draft (.txt)
      responses:
        '200':
          description: Returns draft in requested format.
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        '400':
          description: Error has occured.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error description
